name = "agentchat-agents"
main = "src/index.ts"
compatibility_date = "2025-02-01"
compatibility_flags = ["nodejs_compat"]

[vars]
ENVIRONMENT = "dev"
CLOUDFLARE_AIG_TOKEN = ""
DATABASE_URL = ""
GC_PUBLIC_KEY = ""
SECRETS_ENCRYPTION_KEY = ""
